# screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

TETRIS_BIT_16_SHEET = "assets/graphics/tetris_bit_16.png"
TETRIS_BIT_16_WIDTH = 16
TETRIS_BIT_16_HEIGHT = 16
TETRIS_BIT_16_SHEET_LENGTH = 11

PLAY_AREA_HORIZONTAL_BORDER = "assets/graphics/pipe_16.png"
PLAY_AREA_VERTICAL_BORDER = "assets/graphics/pipe_8.png"

TETRIS_BIT_24_SHEET = "assets/graphics/tetris_bit_24.png"
TETRIS_BIT_24_WIDTH = 24
TETRIS_BIT_24_HEIGHT = 24
TETRIS_BIT_24_SHEET_LENGTH = 11

BOARD_WIDTH = 10
BOARD_HEIGHT = 20